# Generated by Django 2.2.3 on 2019-08-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.CreateModel(
            name='AutorLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Libro')),
            ],
        ),
    ]
