# Generated by Django 2.2.3 on 2019-08-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190821_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='api.Autor'),
        ),
        migrations.DeleteModel(
            name='AutorLibro',
        ),
    ]
